
import dearpygui.dearpygui as dpg
import os
import json

DATAPACK_FOLDER = None
TARGET_FUNCTION = "tick"
NODE_REGISTRY = {}
PORT_REGISTRY = {}
dpg.create_context()
LINKS = set()



def save_project(path):
    project_data = {
        "project": {
            "datapack_folder": DATAPACK_FOLDER,
            "namespace": "built_pack",
            "target_function": "tick"
        },
        "nodes": [serialize_node(n) for n in NODE_REGISTRY.values()],
        "links": serialize_links(),
        "target_function": TARGET_FUNCTION
    }

    with open(path, "w") as f:
        json.dump(project_data, f, indent=2)

def ensure_datapack_structure(base_folder, namespace):
    # pack.mcmeta
    mcmeta_path = os.path.join(base_folder, "pack.mcmeta")
    if not os.path.exists(mcmeta_path):
        with open(mcmeta_path, "w") as f:
            json.dump({
                "pack": {
                    "pack_format": 26,
                    "description": "Generated by Node Editor"
                }
            }, f, indent=2)

    # Required folders
    os.makedirs(os.path.join(base_folder, "data", namespace, "functions"), exist_ok=True)
    os.makedirs(os.path.join(base_folder, "data", "minecraft", "tags", "functions"), exist_ok=True)

    # load.json
    load_tag = os.path.join(base_folder, "data", "minecraft", "tags", "functions", "load.json")
    if not os.path.exists(load_tag):
        with open(load_tag, "w") as f:
            json.dump({"values": [f"{namespace}:load"]}, f, indent=2)

    # tick.json
    tick_tag = os.path.join(base_folder, "data", "minecraft", "tags", "functions", "tick.json")
    if not os.path.exists(tick_tag):
        with open(tick_tag, "w") as f:
            json.dump({"values": [f"{namespace}:tick"]}, f, indent=2)

def choose_folder_callback(sender, app_data):
    global DATAPACK_FOLDER
    DATAPACK_FOLDER = app_data["current_path"]
    print("Selected folder:", DATAPACK_FOLDER)

NODE_REGISTRY = {}
PORT_REGISTRY = {}
TARGET_FUNCTION = "tick"


def datapack_folder_selected(sender, app_data, user_data):
    global DATAPACK_FOLDER
    DATAPACK_FOLDER = app_data["current_path"]
    print("Selected datapack folder:", DATAPACK_FOLDER)

def select_datapack_folder(sender, app_data, user_data):
    dpg.show_item("DatapackFolderDialog")

with dpg.file_dialog(
        directory_selector=True,
        show=False,
        callback=datapack_folder_selected,
        tag="DatapackFolderDialog"
):
    dpg.add_file_extension(".*")


if True:
    #BASE
    class node:
        def __init__(self, name, pos=(0, 0)):
            self.links = set()
            self.name = name
            self.pos = pos
            self.inputs = []
            self.outputs = []
            self.node_id = None
            self.input_ids = []
            self.output_ids = []
            self.upstream = []
            self.downstream = []

        @property
        def type_name(self):
            return self.__class__.__name__

        def setup(self):
            with dpg.node(label=self.name, pos=self.pos, parent="editor") as self.node_id:
                NODE_REGISTRY[self.node_id] = self

                # INPUT PORTS
                for label in self.inputs:
                    with dpg.node_attribute(attribute_type=dpg.mvNode_Attr_Input) as attr_id:
                        dpg.add_text(label)
                        self.input_ids.append(attr_id)
                        PORT_REGISTRY[attr_id] = self

                # INTERNAL UI
                self.build_internal_ui()

                # OUTPUT PORTS
                for label in self.outputs:
                    with dpg.node_attribute(attribute_type=dpg.mvNode_Attr_Output) as attr_id:
                        dpg.add_text(label)
                        self.output_ids.append(attr_id)
                        PORT_REGISTRY[attr_id] = self

                # Right-click delete popup
                with dpg.popup(self.node_id, mousebutton=dpg.mvMouseButton_Right):
                    dpg.add_menu_item(label="Delete Node", callback=lambda: delete_node(self))
        #UI
        def build_internal_ui(self):
            pass


        #CONNECT
        def connect(self, other):
            self.upstream.append(other)
            other.downstream.append(self)


        #BUILD
        def build(self):
            return f"<{self.name} has no build()>"

        #SIGNALS
        def signal(self, data=None):
            for node in self.downstream:
                node.on_signal(self, data)

        def on_signal(self, sender, data):
            pass

        def load_params(self, params):
            # Default: do nothing
            pass


    #ADD SCOREBOARD OBJECTIVE
    class ScoreboardAddObjectiveNode(node):
        def __init__(self, pos=(0,0)):
            super().__init__("Score Obj Add", pos)
            self.inputs = []
            self.outputs = ["Command"]

        def build_internal_ui(self):
            with dpg.node_attribute(attribute_type=dpg.mvNode_Attr_Static):
                self.name = dpg.add_input_text(label="Name", default_value="points")
                self.criteria = dpg.add_input_text(label="Criteria", default_value="dummy")

        def get_params(self):
            return {"name": dpg.get_value(self.name), "criteria": dpg.get_value(self.criteria)}

        def build(self):
            name = dpg.get_value(self.name)
            crit = dpg.get_value(self.criteria)
            return f"scoreboard objectives add {name} {crit}"

        def load_params(self, params):
            dpg.set_value(self.name, params["name"])
            dpg.set_value(self.criteria, params["criteria"])


    #ENTITY SELECTOR
    class SelectorNode(node):
        def __init__(self, pos=(0,0)):
            super().__init__("@e", pos)
            self.outputs = ["Selector"]
        def get_params(self):
            pass
        def build(self):
            return "@e"
        def load_params(self,params):
            pass

    #NEAREST PLAYER SELECTOR
    class NearPlayerSelectorNode(node):
        def __init__(self, pos=(0,0)):
            super().__init__("@n", pos)
            self.outputs = ["Selector"]

        def build(self):
            return "@p"
        def get_params(self):
            pass
        def load_params(self,params):
            pass

    #ALL PLAYER SELECTOR
    class AllPlayerSelectorNode(node):
        def __init__(self, pos=(0,0)):
            super().__init__("@a", pos)
            self.outputs = ["Selector"]

        def build(self):
            return "@a"
        def get_params(self):
            pass
        def load_params(self,params):
            pass

    #NEAREST ENTITY
    class NearEntitySelectorNode(node):
        def __init__(self, pos=(0,0)):
            super().__init__("@n", pos)
            self.outputs = ["Selector"]

        def build(self):
            return "@n"
        def get_params(self):
            pass
        def load_params(self,params):
            pass

    #AS
    class ExecuteAsNode(node):
        def __init__(self, pos=(0,0)):
            super().__init__("ExecuteAs", pos)
            self.inputs = ["Selector", "Command"]
            self.outputs = ["Command"]

        def build(self):
            selector = self.upstream[0].build()
            inner = self.upstream[1].build()
            return f"execute as {selector} run {inner}"
        def get_params(self):
            pass

        def load_params(self,params):
            pass

    #SAY
    class SayNode(node):
        def __init__(self, pos=(0,0)):
            super().__init__("Say", pos)
            self.inputs = []
            self.outputs = ["COMMAND"]

        def build_internal_ui(self):
            with dpg.node_attribute(attribute_type=dpg.mvNode_Attr_Static):
                self.msg = dpg.add_input_text(label="Message",default_value="Hello World",width=120)

        def get_params(self):
            return {"msg": dpg.get_value(self.msg)}

        def build(self):
            text = dpg.get_value(self.msg)
            return "say \"" + text +"\""

        def load_params(self, params):
            dpg.set_value(self.msg, params["msg"])

    #KILL
    class KillNode(node):
        def __init__(self, pos=(0,0)):
            super().__init__("Kill", pos)
            self.inputs = ["Selector"]
            self.outputs = ["Command"]

        def build(self):
            if not self.upstream:
                return "<Kill missing selector>"
            selector = self.upstream[0].build()
            return f"kill {selector}"

        def load_params(self,params):
            pass

    #AT
    class ExecuteAtNode(node):
        def __init__(self, pos=(0,0)):
            super().__init__("ExecuteAt", pos)
            self.outputs = ["Command"]
            self.inputs = ["COMMAND"]

        def build_internal_ui(self):
            with dpg.node_attribute(attribute_type=dpg.mvNode_Attr_Static):
                self.x = dpg.add_input_float(label="x",default_value=0,width=120)
                self.y = dpg.add_input_float(label="y",default_value=0,width=120)
                self.z = dpg.add_input_float(label="z",default_value=0,width=120)

        def get_params(self):
            return {"x":dpg.get_value(self.x),"y":dpg.get_value(self.y),"z":dpg.get_value(self.z)}

        def build(self):
            inner = self.upstream[0].build()
            x = dpg.get_value(self.x)
            y = dpg.get_value(self.y)
            z = dpg.get_value(self.z)
            return f"execute at {x} {y} {z} run {inner}"

        def load_params(self, params):
            dpg.set_value(self.x, params["x"])
            dpg.set_value(self.y, params["y"])
            dpg.set_value(self.z, params["z"])

    #SELECTOR MOD
    class SelectorModifierNode(node):
        def __init__(self, pos=(0,0)):
            super().__init__("SelectorModifier", pos)
            self.inputs = ["Selector"]
            self.outputs = ["Selector"]

        def build_internal_ui(self):
            with dpg.node_attribute(attribute_type=dpg.mvNode_Attr_Static):
                self.key = dpg.add_input_text(label="Key", default_value="type",width=120)
                self.value = dpg.add_input_text(label="Value", default_value="frenchfry",width=120)

        def get_params(self):
            return {"key":dpg.get_value(self.key),"value":dpg.get_value(self.value)}

        def build(self):
            base = self.upstream[0].build()
            key = dpg.get_value(self.key)
            value = dpg.get_value(self.value)

            # If selector has no brackets, add them
            if "[" not in base:
                return f"{base}[{key}={value}]"

            # If selector already has brackets, insert before closing ]
            return base[:-1] + f",{key}={value}]"

        def load_params(self, params):
            dpg.set_value(self.key, params["key"])
            dpg.set_value(self.value, params["value"])

    #END
    class EndNode(node):
        def __init__(self, pos=(0,0)):
            super().__init__("End", pos)
            self.inputs = ["Command"]

        def build_internal_ui(self):
            with dpg.node_attribute(attribute_type=dpg.mvNode_Attr_Static):
                self.priority = dpg.add_input_int(label="Order", default_value=0,width=120)

        def get_params(self):
            return {"priority":dpg.get_value(self.priority)}

        def build(self):
            if not self.upstream:
                return "<End node missing command input>"
            return self.upstream[0].build()

        def load_params(self,params):
            pass

    #TP TO POSITON
    class TpPosNODE(node):
        def __init__(self, pos=(0,0)):
            super().__init__("TP to Pos", pos)
            self.z = None
            self.x = None
            self.y = None
            self.inputs = []
            self.outputs = ["COMMAND"]

        def build_internal_ui(self):
            with dpg.node_attribute(attribute_type=dpg.mvNode_Attr_Static):
                self.x = dpg.add_input_float(label="x", default_value=0, width=120)
                self.y = dpg.add_input_float(label="y", default_value=0, width=120)
                self.z = dpg.add_input_float(label="z", default_value=0, width=120)

        def get_params(self):
            return {"x":dpg.get_value(self.x),"y":dpg.get_value(self.y),"z":dpg.get_value(self.z)}

        def build(self):
            x = dpg.get_value(self.x)
            y = dpg.get_value(self.y)
            z = dpg.get_value(self.z)

            return f"tp {x} {y} {z}"

        def load_params(self, params):
            dpg.set_value(self.x, params["x"])
            dpg.set_value(self.y, params["y"])
            dpg.set_value(self.z, params["z"])

    #EXECUTE IF SCORE
    class ExecuteIfScoreNode(node):
        def __init__(self, pos=(0,0)):
            super().__init__("ExecuteIfScore", pos)
            self.inputs = ["Command"]     # ONE input
            self.outputs = ["Command"]

        def build_internal_ui(self):
            with dpg.node_attribute(attribute_type=dpg.mvNode_Attr_Static):
                self.target = dpg.add_input_text(label="Target", default_value="@s", width=120)
                self.objective = dpg.add_input_text(label="Objective", default_value="points", width=120)
                self.min = dpg.add_input_int(label="Min", default_value=1)
                self.max = dpg.add_input_int(label="Max", default_value=999999)

        def get_params(self):
            return {"target":dpg.get_value(self.target),"objective":dpg.get_value(self.objective),"min":dpg.get_value(self.min),"max":dpg.get_value(self.max)}

        def build(self):
            if not self.upstream:
                return "<ExecuteIfScore missing command>"

            inner = self.upstream[0].build()

            target = dpg.get_value(self.target)
            obj = dpg.get_value(self.objective)
            mn = dpg.get_value(self.min)
            mx = dpg.get_value(self.max)

            return f"execute if score {target} {obj} matches {mn}..{mx} run {inner}"

        def load_params(self, params):
            dpg.set_value(self.target, params["target"])
            dpg.set_value(self.objective, params["objective"])
            dpg.set_value(self.min, params["min"])
            dpg.set_value(self.max, params["max"])

    #ADD TO PLAYER OBJECTIVE
    class ScoreboardSetNode(node):
        def __init__(self, pos=(0,0)):
            super().__init__("Score Set", pos)
            self.inputs = ["Selector"]
            self.outputs = ["Command"]

        def build_internal_ui(self):
            with dpg.node_attribute(attribute_type=dpg.mvNode_Attr_Static):
                self.objective = dpg.add_input_text(label="Objective", default_value="points")
                self.value = dpg.add_input_int(label="Value", default_value=0)

        def get_params(self):
            return {"objective":dpg.get_value(self.objective),"value":dpg.get_value(self.value)}

        def build(self):
            if not self.upstream:
                return "<ScoreSet missing selector>"
            selector = self.upstream[0].build()
            obj = dpg.get_value(self.objective)
            val = dpg.get_value(self.value)
            return f"scoreboard players set {selector} {obj} {val}"

        def load_params(self, params):
            dpg.set_value(self.objective, params["objective"])
            dpg.set_value(self.value, params["value"])


    #EXTRAS
    class ExtraCommandNode(node):
        def __init__(self, pos=(0,0)):
            super().__init__("ExtraCommand", pos)
            self.inputs = []
            self.outputs = ["Command"]

        def build_internal_ui(self):
            with dpg.node_attribute(attribute_type=dpg.mvNode_Attr_Static):
                self.cmd = dpg.add_input_text(label="Command", default_value="", width=200)

        def get_params(self):
            return {"cmd":dpg.get_value(self.cmd)}

        def build(self):
            text = dpg.get_value(self.cmd)
            return text

        def load_params(self, params):
            dpg.set_value(self.cmd, params["cmd"])

    #SUMMON
    class SummonNode(node):
        def __init__(self, pos=(0,0)):
            super().__init__("Summon", pos)
            self.inputs = []
            self.outputs = ["Command"]

        def build_internal_ui(self):
            with dpg.node_attribute(attribute_type=dpg.mvNode_Attr_Static):
                self.entity = dpg.add_input_text(label="Entity", default_value="minecraft:zombie", width=150)
                self.x = dpg.add_input_float(label="x", default_value=0)
                self.y = dpg.add_input_float(label="y", default_value=0)
                self.z = dpg.add_input_float(label="z", default_value=0)
                self.nbt = dpg.add_input_text(label="nbt", default_value="   ")

        def get_params(self):
            return {"entity":dpg.get_value(self.entity),"x":dpg.get_value(self.x),"y":dpg.get_value(self.y),"z":dpg.get_value(self.z),"nbt":dpg.get_value(self.nbt)}

        def build(self):
            ent = dpg.get_value(self.entity)
            x = str(dpg.get_value(self.x))
            y = str(dpg.get_value(self.y))
            z = str(dpg.get_value(self.z))
            return "summon " + ent + " " + x + " " + y + " " + z + " {" +str(dpg.get_value(self.nbt)) +"}"

        def load_params(self, params):
            dpg.set_value(self.entity, params["entity"])
            dpg.set_value(self.x, params["x"])
            dpg.set_value(self.y, params["y"])
            dpg.set_value(self.z, params["z"])
            dpg.set_value(self.nbt, params["nbt"])

    #FUNCTION
    class FunctionNode(node):
        def __init__(self, pos=(0,0)):
            super().__init__("ExtraCommand", pos)
            self.inputs = []
            self.outputs = ["Command"]

        def build_internal_ui(self):
            with dpg.node_attribute(attribute_type=dpg.mvNode_Attr_Static):
                self.cmd = dpg.add_input_text(label="Function", default_value="", width=200)

        def get_params(self):
            return {"cmd":dpg.get_value(self.cmd)}

        def build(self):
            text = dpg.get_value(self.cmd)
            return "function "+text

        def load_params(self, params):
            dpg.set_value(self.cmd, params["cmd"])


#BASE UTILS

def clear_graph():
    # Delete links first
    for link_id in list(LINKS):
        try:
            dpg.delete_item(link_id)
        except:
            pass
    LINKS.clear()

    # Delete nodes
    for node_id in list(NODE_REGISTRY.keys()):
        try:
            dpg.delete_item(node_id)
        except:
            pass
    NODE_REGISTRY.clear()
    # Reset counters if you use them
    NODE_ID_COUNTER = 0
    LINK_ID_COUNTER = 0
    # Reset internal registries
    NODE_REGISTRY.clear()
    PORT_REGISTRY.clear()

def serialize_node(node):
    return {
        "id": node.node_id,
        "type": node.type_name,
        "pos": dpg.get_item_pos(node.node_id),
        "params": node.get_params()  # you implement this per node type
    }

#_original_add_input_text = dpg.add_input_text
#_original_add_input_int = dpg.add_input_int
# etc...

#def auto_param_register(func):
#    def wrapper(*args, **kwargs):
#        widget_id = func(*args, **kwargs)
#
#        # Find the current node being built
#        func_node = node._current_node
#        if func_node is not None:
#            label = kwargs.get("label", None)
#            if label:
#                func_node.param_widgets[label] = widget_id
#
#        return widget_id
#    return wrapper

# Patch DPG

def serialize_links():
    links = []
    for node in NODE_REGISTRY.values():
        for link_id in node.links:
            info = dpg.get_item_configuration(link_id)
            links.append({
                "from_port": info["attr_1"],
                "to_port":   info["attr_2"]
            })
    return links


project_data = {
    "project": {
        "datapack_folder": DATAPACK_FOLDER,
        "namespace": "built_pack",
        "target_function": "tick"
    },
    "nodes": [serialize_node(n) for n in NODE_REGISTRY.values()],
    "links": serialize_links()
}

def load_project(path):
    data = json.load(open(path))
    global TARGET_FUNCTION

    # Create nodes
    for n in data["nodes"]:
        node_class = LOADING_TYPES[n["type"]]
        node = node_class(pos=n["pos"])

        # FIX: ensure node is created inside the editor
        dpg.push_container_stack("editor")
        node.setup()
        dpg.pop_container_stack()

        node.load_params(n["params"])

    for link in data["links"]:
        out_port = link["from_port"]
        in_port = link["to_port"]

        link_id = dpg.add_node_link(out_port, in_port, parent="editor")

        # Track link in nodes
        src_node = PORT_REGISTRY[out_port]
        dst_node = PORT_REGISTRY[in_port]

        src_node.links.add(link_id)
        dst_node.links.add(link_id)

        dst_node.connect(src_node)

    TARGET_FUNCTION = data["project"]["target_function"]
    dpg.set_value("CustomFunctionName", TARGET_FUNCTION)
    TARGET_FUNCTION = data["project"]["target_function"]

def get_params(self):
    return {}

def set_target_function(value):
    global TARGET_FUNCTION

    if value == "custom":
        dpg.configure_item("CustomFunctionName", enabled=True)
        TARGET_FUNCTION = dpg.get_value("CustomFunctionName")
    else:
        dpg.configure_item("CustomFunctionName", enabled=False)
        TARGET_FUNCTION = value

    clear_graph()


def update_custom_function(sender, app_data):
    global TARGET_FUNCTION
    TARGET_FUNCTION = app_data

def on_link(sender, app_data):
    if not dpg.does_item_exist("editor"):
        print("Link ignored: NodeEditor does not exist")
        return

    link_id = dpg.add_node_link(app_data[0], app_data[1], parent="editor")
    LINKS.add(link_id)

    output_port = app_data[0]
    input_port  = app_data[1]

    # Create the visual link
    link_id = dpg.add_node_link(output_port, input_port, parent="editor")

    # Find the nodes that own these ports
    src_node = PORT_REGISTRY[output_port]
    dst_node = PORT_REGISTRY[input_port]

    # Track the link so we can delete it later
    src_node.links.add(link_id)
    dst_node.links.add(link_id)

    # Track graph connections
    dst_node.connect(src_node)

def on_delink(sender, app_data):
    link_id = app_data
    LINKS.discard(link_id)

def set_datapack_folder(sender, app_data):
    global DATAPACK_FOLDER
    DATAPACK_FOLDER = app_data["file_path_name"]
    print("Datapack folder set to:", DATAPACK_FOLDER)


def build_graph():
    global DATAPACK_FOLDER

    if not DATAPACK_FOLDER:
        dpg.set_value("OutputBox", "Select a datapack folder first.")
        return

    ensure_datapack_structure(DATAPACK_FOLDER, "built_pack")
    ends = [n for n in NODE_REGISTRY.values() if isinstance(n, EndNode)]
    if not ends:
        dpg.set_value("OutputBox", "No End node found")
        return

    ends.sort(key=lambda n: dpg.get_item_pos(n.node_id)[1])
    try:
        output = "\n".join(end.build() for end in ends)
    except:
        print("Build failed")
        output = "Error"

    # Show in UI
    dpg.set_value("OutputBox", output)

    # Ask user which function to write to
    # (you can replace this with a dropdown later)
    target = "tick"  # or "load"

    # Ask for namespace (or auto-detect)
    namespace = "mynamespace"

    # Build full path
    func_path = os.path.join(
        DATAPACK_FOLDER,
        "data",
        namespace,
        "functions",
        f"{TARGET_FUNCTION}.mcfunction"
    )

    os.makedirs(os.path.dirname(func_path), exist_ok=True)
    with open(func_path, "w") as f:
        f.write(output)

    if TARGET_FUNCTION in ("tick", "load"):
        tag_path = os.path.join(
            DATAPACK_FOLDER,
            "data",
            "minecraft",
            "tags",
            "functions",
            f"{TARGET_FUNCTION}.json"
        )

        tag_value = f"{namespace}:{TARGET_FUNCTION}"

        if os.path.exists(tag_path):
            with open(tag_path, "r") as f:
                data = json.load(f)
        else:
            data = {"values": []}

        if tag_value not in data["values"]:
            data["values"].append(tag_value)

        with open(tag_path, "w") as f:
            json.dump(data, f, indent=2)

        os.makedirs(os.path.dirname(tag_path), exist_ok=True)

    # Ensure folders exist
    os.makedirs(os.path.dirname(func_path), exist_ok=True)

    # Write file
    if not output == "Error":
        with open(func_path, "w") as f:
            f.write(output)

        print("Wrote to:", func_path)
        if TARGET_FUNCTION not in ("tick", "load"):
            # no tag file needed
            pass

def resize_layout():
    total_h = dpg.get_viewport_height()

    editor_h = int(total_h * 0.78)   # 80%
    bottom_h = int(total_h * 0.10)   # 20%

    dpg.configure_item("EditorRegion", height=editor_h)
    dpg.configure_item("BottomBar", height=bottom_h)

def spawn_node(sender, app_data, node_type_name):
    node_class = NODE_TYPES[node_type_name]

    # Switch context to the node editor
    dpg.push_container_stack("editor")

    mouse = dpg.get_mouse_pos(local=False)
    editor_pos = dpg.get_item_rect_min("editor")
    pos = (mouse[0] - editor_pos[0], mouse[1] - editor_pos[1])

    n = node_class(pos=pos)
    n.setup()

    # Pop back out
    dpg.pop_container_stack()

def delete_node(node):
    # Delete all links connected to this node
    for link_id in list(node.links):
        dpg.delete_item(link_id)

    # Delete the node UI
    dpg.delete_item(node.node_id)

    # Remove from registry
    if node.node_id in NODE_REGISTRY:
        del NODE_REGISTRY[node.node_id]


def save_to_main():
    global output
    if DATAPACK_FOLDER:
        try:
            with open(TARGET_FUNCTION+".weave", "x") as file:
                #file.write("This line is written using exclusive mode.")
                pass
        except FileExistsError:
            #print("Error: The file already exists. Aborting to prevent data loss.")
            pass
        save_project(DATAPACK_FOLDER+"\\"+TARGET_FUNCTION+".weave")

def load_from_main():
    if DATAPACK_FOLDER:
        try:
            load_project((DATAPACK_FOLDER+"\\"+TARGET_FUNCTION+".weave"))
            output = "Loaded"
            print(output)

        except:
            output = "No save. Did you choose the correct folder and function?"
            print(output)
    #load_project("main.weave")

LOADING_TYPES = {}


NODE_TYPES = {
    "All Entities": SelectorNode,
    "ExecuteAs": ExecuteAsNode,
    "ExecuteAt": ExecuteAtNode,
    "Say": SayNode,
    "SelectorModifier": SelectorModifierNode,
    "TpPos": TpPosNODE,
    "End":EndNode,
    "Nearest Entity": NearEntitySelectorNode,
    "Nearest Player": NearPlayerSelectorNode,
    "All Players": AllPlayerSelectorNode,
    "Objective": ScoreboardAddObjectiveNode,
    "Scoreboard Set": ScoreboardSetNode,
    "Execute If Score": ExecuteIfScoreNode,
    "Summon": SummonNode,
    "Kill": KillNode,
    "Extra": ExtraCommandNode,
    "Function": FunctionNode,
}

for i in NODE_TYPES:
    LOADING_TYPES[NODE_TYPES[i].__name__] = NODE_TYPES[i]


#end_node = EndNode()


dpg.create_context()
dpg.create_viewport(title="PackWeaver")

# Create the dialog BEFORE the UI tries to show it
with dpg.file_dialog(directory_selector=True, show=False, callback=set_datapack_folder, tag="DatapackDialog"):
    dpg.add_file_extension(".*")

with dpg.window(label="Graph", tag="Graph"):
    dpg.add_menu_item(label="Select Datapack Folder", callback=select_datapack_folder)

    with dpg.menu_bar():
        with dpg.menu(label="Function"):
            dpg.add_combo(
                label="Build Into",
                items=["tick", "load", "custom"],
                default_value="tick",
                callback=lambda s, a: set_target_function(a)
            )
            dpg.add_input_text(
                label="Custom Function",
                tag="CustomFunctionName",
                default_value="",
                enabled=False
            )

        with dpg.menu(label="Add Node"):
            for name in NODE_TYPES:
                dpg.add_menu_item(label=name, callback=spawn_node, user_data=name)
        dpg.add_menu_item(label="Build", callback=build_graph)

        with dpg.menu(label="Save"):
            dpg.add_menu_item(label="Save", callback=save_to_main)

        with dpg.menu(label="Load"):
            dpg.add_menu_item(label="Load", callback=load_from_main)



    with dpg.group(horizontal=False):

        # Node editor region (height will be overwritten)
        with dpg.child_window(
            tag="EditorRegion",
            autosize_x=True,
            height=300,     # temporary
            no_scrollbar=True,
            border=False
        ):
            with dpg.node_editor(tag="editor", callback=on_link):
                pass

        # Bottom bar (height will be overwritten)
        with dpg.child_window(
            tag="BottomBar",
            autosize_x=True,
            height=100,     # temporary
            no_scrollbar=True
        ):
            dpg.add_text("Output:")
            dpg.add_input_text(
                tag="OutputBox",
                multiline=True,
                readonly=True,
                width=-1,
                height=-1
            )

dpg.set_primary_window("Graph", True)
dpg.set_viewport_resize_callback(lambda: resize_layout())
dpg.setup_dearpygui()
dpg.show_viewport()
dpg.start_dearpygui()
dpg.destroy_context()